language: node_js
node_js:
- 0.10
notifications:
  email:
  - damon.oehlman@nicta.com.au
  irc: irc.freenode.org#rtc.io
env:
  global:
  - secure: Xo5DDUYF9ieE9uzku88im0W/iQrDM/XMxdr4SsXQwVy+v6Y7gMQwPnIlBicgitq7B1ZoVnSrPO0XkNSsj2RYgPUDKLJzQPozp5LiiDOydBC2CpCr6DFlinovwQdm8U64zvvh8m8DIH8Ow1BZmfqHo616DBV1LRToXpMl/fj9+0w=
  - secure: P120lzsmhYQZdFz6/sIDjeDpjJH7D8rID1JIf6AEfBbQ94urY5iJ15awQFp7G2b268ekHbyz0LwTgXVakf/WcclUNCPQxPj8wlRbdDE0zL6nmfMWyoM/gGnTrPjtfoONn1e9DIpNqIc/AXI+abcuaio+8OmkBfxAJvIcX5nB6iI=
