language: node_js
node_js:
- 0.1
notifications:
  email:
  - damon.oehlman@nicta.com.au
  irc: irc.freenode.org#rtc.io
env:
  global:
  - secure: iJ1L4gVrdvcATow4FcyeeqBCgxOqK99f414i227e/5xw2Kd0Q9KGSVTyhThmCXR9MbxeyVAoX4gNzY715S2URe8Gu3MEUDPrw+qi4zeUADeqf9kiPtllHUa25xn0bKHElVxC78rP+fewDy0lq9/P5MXYybyRBPuhpKf6a1eV1VE=
  - secure: DaW+/139NhqC42bzhc/7MteEEzbuCAVe7Py2B5wZ52Rfmm5F0clw35pdULr7OE5/lIvvsjy+8FgIzHW2OFL09r979xW236/MFIbXFgABP1XztaaLpOGymvLHv1n32LQqXd5w8JbB2QsZqURXdn+FDIOU7i5GL5OSpPJs9rrlrx4=
